name: permit
description: A sample command-line application with basic argument parsing.
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

executables:
  permit: permit

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  xml: ^6.6.1
  path: ^1.9.1
  interact: ^2.2.0
  collection: ^1.19.1
  ansicolor: ^2.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
