name: permit
description: The zero-config, manifest-driven permission bridge for Flutter.
version: 0.1.0+2
repository: https://github.com/Milad-Akarie/permit

screenshots:
  - description: 'Permit Logo'
    path: art/permit_logo.png
topics:
  - permissions
  - runtime-permissions
  - permission-handling
  - permission-handler
  - plugin


environment:
  sdk: ^3.10.4

executables:
  permit: permit

dependencies:
  args: ^2.7.0
  xml: ^6.6.1
  path: ^1.9.1
  interact: ^2.2.0
  collection: ^1.19.1
  ansicolor: ^2.0.3
  yaml: ^3.1.3
  yaml_edit: ^2.2.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  coverage: ^1.15.0
